server:
  port:
    9002
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9020/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
spring:
  application:
    name: gatewayService
  cloud:
    config:
      enabled: true
    gateway:
      mvc:
        routes[0]:
          id: customerservice
          predicates[0]: Path=/individualcustomerservice/api/v1/customers/**
          uri: lb://CUSTOMERSERVICE
        routes[1]:
          id: orderservice
          predicates[0]: Path=/orderservice/api/v1/orders/**
          uri: lb://ORDERSERVICE
        routes[2]:
          id: discoveryserver
          predicates[0]: Path=/eureka/web
          filters[0]: SetPath=/
          uri: http://localhost:9020
        



