server:
  port:
    9002
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9020/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
spring:
  application:
    name: gatewayService
  cloud:
    config:
      enabled: true
    gateway:
      mvc:
        routes[0]:
          id: customerservice
          predicates[0]: Path=/api/v1/customers/**
          uri: lb://CUSTOMERSERVICE
        routes[1]:
          id: orderservice
          predicates[0]: Path=/orderservice/api/v1/orders/**
          uri: lb://ORDERSERVICE
        routes[2]:
          id: discoveryserver
          predicates[0]: Path=/eureka/web
          filters[0]: SetPath=/
          uri: http://localhost:9020
        routes[3]:
          id: accountservice
          predicates[0]: Path=/accountservice/api/v1/accounts/**
          uri: lb://ACCOUNTSERVICE
        routes[4]:
          id: basketservice
          predicates[0]: Path=/api/v1/basket/**
          uri: lb://BASKETSERVICE
        routes[5]:
          id: catalogservice
          predicates[0]: Path=/catalogservice/api/v1/products/**
          uri: lb://CATALOGSERVICE
        routes[6]:
          id: identityservice
          predicates[0]: Path=/api/v1/auth/**
          uri: lb://IDENTITYSERVICE
        routes[7]:
          id: searchservice
          predicates[0]: Path=/searchservice/api/v1/customers/**
          uri: lb://SEARCHSERVICE


